
stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  only:
    - main
  when: manual
  script:
    - chmod 600 $DEPLOY_SSH
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add $DEPLOY_SSH
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # deploy core everywere
    - scp build/ -i -p 198 $DEPLOY_SSH root@hiroshi:/home/geekland/front
    - ssh -i $DEPLOY_SSH -p 198 root@$185.157.247.242 'screen -x geekfront'
    - ssh -i $DEPLOY_SSH -p 198 root@$185.157.247.242 'serve'



